export const GETHOME = 'GETHOME'
export const CATEGORY = 'CATEGORY'
export const GOODETAIL = 'GOODETAIL'
export const CHANGEBUYCOUNT = 'CHANGEBUYCOUNT'
export const DELETEGOOD = 'DELETEGOOD'
export const DELETEMOREGOODS = 'DELETEMOREGOODS'

//shopcart
export const SHOPCART = 'SHOPCART'
export const TOGGLESHOP = 'TOGGLESHOP'
export const TOGGLEGOOD = 'TOGGLEGOOD'
export const SHOPTOGGLE = 'SHOPTOGGLE'
export const ONECHECKEDSHOP = 'ONECHECKEDSHOP'